name: Build WPF CRYPTOBOT

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: PROG_POE.sln

    steps:
      - name:  Checkout Repository
        uses: actions/checkout@v4

      - name:  Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name:  Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name:  Restore NuGet Packages
        run: msbuild $env:Solution_Name /t:Restore

      - name:  Build Solution
        run: msbuild $env:Solution_Name /p:Configuration=Release

      - name:  Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: Build-Artifacts
          path: '**/bin/Release/**'
